
meta_product_name: "Meine Kita in Berlin"
meta_title: "Meine Kita in Berlin - Der einfachste Weg deine Kitasuche zu organisieren"
meta_description: "Finde Kitas in deiner N채he, filtere nach Pr채ferenzen wie Sprachen, P채dagogischen Ans채tzen u.v.m., speicher deine Favoriten, erstell dir Kontaktreminder oder kontaktiere passende Kitas einfach direkt."
meta_image: "meinekita.png"                       # should exist in `app/assets/images/`
