toolbar:
  - styleselect | bold italic | undo redo link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat
  - image | link | formatselect
plugins:
  - image
  - link
